### PR TITLE
More updates

### PR DESCRIPTION
**Pull request by bpamiri**
I've made some progress here and I think the app creation may be ready for prime time. So here are the changes:

- I abandoned the wheels create name space and moved the app command into the wheels generate name space. 
- The wheels generate app command allows the creation of an app by specifying the app name, template name, directory, reload password, datasource name, CFML engine, whether a H2 database should be setup, and whether the directory should be initialized as a ForgBox package. None of the parameters are required. At the most basic an app with the name MyCFWheelsApp will be created in a subdirectory called MyCFWheels using the Base template. By default the reload password will be changeMe, the datasource name will be MyCFWheels, and Lucee will be setup as the CFML engine. By default the H2 database will not be setup and the directory will not be initialized as a package.
- If an app name is passed to wheels generate app that name will be used as the sub directory name and the datasource name if those parameters are not provided.
- There is a check to make sure the target directory is empty before proceeding.
- The wheels app command doesn't require any inputs to enable it to be used for scripting purposes.
- There is also a new wheels generate app-wizard. This command is aliased as wheels g app-wizard as well as wheels new. So it replaces the old wheels new command. This is the new wizard and prompts the user for every parameter and provides detailed menus to select from. Once all parameters have been gathered this command calls the wheels g app command to do the actual work. This way the actual site creation logic is only in one place.
- The wheels-base template that all the templates use has been updated with the CLI placeholders needed for the app creation i.e. |appName|, |datasourceName|, |reloadPassword|, |cfmlEngine|, and // CLI-Appends-Here.

I need to check the H2 database. I was getting some errors when trying to create a migration file from the GUI. I put that aside till I get this base files created. Then I'll move on to the other generation commands and test and run them. I figured I'll hit the H2 database issue quickly if there really is an issue there. I really want to get a local database solution functional so I can write some tutorials like the many Rails tutorial that use the CLI to create the db and migrations.

Anyway that's enough rambling for now.

### CODE REVIEW

**Comment by neokoenig** [comment]
If there are H2 migration errors, it's more likely to be the wheels adapter; I don't know of many people who actively use H2 (apart from early wheels core testing to mock oracle!).

**Comment by bpamiri** [comment]
I’m just trying to make sure we have a viable local DB option. I intend to write some tutorial by taking some Rails tutorials and rewriting them for Wheels. As you know, in the Rails world they are all about SQLite as the local DB. I’m not particular to any DB but would like to get a local DB working so that can be the default dev DB that we promote.

**Comment by bpamiri** [comment]
I’m also extending this and working on installing the H2 Luce extension automatically so the user has less to do.

**Comment by neokoenig** [comment]
Cool I'll hold off on a merge for now then

**Comment by bpamiri** [comment]
It should be good to go now. The H2 dependency is now properly added to the box.json.

**Comment by bpamiri** [comment]
The final commit modifies the final message displayed to the user about how to install the H2 dependency.

**Comment by bpamiri** [comment]
This is ready to roll.

**Comment by neokoenig** [comment]
Now in 0.5.0

**Pull request merged**
